repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      types: [python]
      language_version: python3.8

-   repo: https://github.com/timothycrosley/isort
    rev: 5.0.7
    hooks:
    - id: isort
      types: [python]
      language_version: python3.8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    - id: mypy
      types: [python]
      language_version: python3.8
