version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: django_docker
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
    db-data: